import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/app/providers';
import { Toaster } from '@/components/ui/toaster';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white dark:bg-[#313338]">
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
